### ISSUE TITLE
Trying to upload certain datasets results in an error.

### ISSUE THREAD

**Issue by salspaugh** [macfarlandian/DataFramer#21]
The error being thrown is `Uncaught RangeError: Invalid string length`. This probably has something to do with the data set size.

**Comment by salspaugh** [comment]
@macfarlandian @annaswigart I think this got resolved a while ago?

**Comment by macfarlandian** [comment]
@salspaugh it's more or less stopped happening but i'm not sure any of us really knows why. but for now it's not a problem so we can close this.
