### ISSUE TITLE
Write client to load test service.

### ISSUE THREAD

**Issue by salspaugh** [macfarlandian/DataFramer#36]
Client should open connection to server and log in -- what else?

**Comment by salspaugh** [comment]
@macfarlandian I think you got this taken care of, right? Are there any scripts or anything you wrote to do this that would be handy to have in the repo?

**Comment by macfarlandian** [comment]
good call, i'll add that.

**Comment by macfarlandian** [comment]
@salspaugh @annaswigart see 3a79ff7b02e689c2b266e06ff3c59fa2eb3e1d23 and new private repo.

for now, the deploy branch is separate from v2. we can rebase as necessary and merge later if we decide that's what we should do.
